/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String pathName = "src/main/resources/manyErrors.js";
        System.out.println(checkLinterError(pathName));
    }

    public static String checkLinterError(String pathName) {
        Scanner gates;
        try {
            gates = new Scanner(new File(pathName));
        } catch (FileNotFoundException e) {
            return "We couldn't find that book, could you get a better filepath?";
        }
        int count = 0;
        String returnString = "";
        if (!gates.hasNext()){return "Empty File!";}
        while (gates.hasNext()) {
            // get each line in the js file
            String nextLine = gates.nextLine();
            //counts each line
            count++;
            if (!nextLine.isEmpty() && !nextLine.contains("if") && !nextLine.contains("else") && !nextLine.endsWith("{") && !nextLine.endsWith("}") && !nextLine.startsWith("//")) {
                char lastChar = nextLine.charAt(nextLine.length() - 1);
                if (lastChar != ';') {
                    returnString += "Line " + count + " is missing semicolon.\n";
                }
            }
        }
        return returnString;
    }
}
