/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Scanner gates;
        try {
            gates = new Scanner(new File("src/main/resources/gates.js"));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("We couldn't find that book, could you get a better filepath?");
            return;
        }
        int count = 0;
        while (gates.hasNext()){
            // get each line in the js file
            String nextLine = gates.nextLine();
            //counts each line
            count ++;
            if (!nextLine.isEmpty()&&!nextLine.contains("if")&&!nextLine.contains("else")&&!nextLine.endsWith("{")&&!nextLine.endsWith("}")&&!nextLine.startsWith("//")) {
                char lastChar = nextLine.charAt(nextLine.length() - 1);
                if (lastChar != ';'){
                    System.out.println("Line " + count + " is missing semicolon." );
                }
            }
        }

    }
}
